CREATE TABLE IF NOT EXISTS habitat_backgrounds (
  id INT AUTO_INCREMENT PRIMARY KEY,
  habitat_slug VARCHAR(50) NOT NULL,
  type_slug VARCHAR(50) NOT NULL,
  display_name VARCHAR(100) NOT NULL,
  image_filename VARCHAR(100) NOT NULL,
  created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  UNIQUE KEY unique_habitat_type (habitat_slug, type_slug)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO habitat_backgrounds (habitat_slug, type_slug, display_name, image_filename) VALUES
-- 1. 동굴 (cave)
('cave', 'bug', '실크 동굴', 'bug.png'),
('cave', 'dark', '어둠의 동굴', 'dark.png'),
('cave', 'dragon', '용의 동굴', 'dragon.png'),
('cave', 'electric', '번개 동굴', 'electric.png'),
('cave', 'fairy', '달빛 동굴', 'fairy.png'),
('cave', 'fighting', '수련의 동굴', 'fighting.png'),
('cave', 'fire', '용암 동굴', 'fire.png'),
('cave', 'flying', '하늘의 동굴', 'flying.png'),
('cave', 'ghost', '망령의 동굴', 'ghost.png'),
('cave', 'grass', '이끼 동굴', 'grass.png'),
('cave', 'ground', '대지의 동굴', 'ground.png'),
('cave', 'ice', '얼음 동굴', 'ice.png'),
('cave', 'poison', '맹독의 동굴', 'poison.png'),
('cave', 'psychic', '염력의 동굴', 'psychic.png'),
('cave', 'rock', '암석 동굴', 'rock.png'),
('cave', 'steel', '금속 동굴', 'steel.png'),
('cave', 'water', '수중 동굴', 'water.png'),
('cave', 'normal', '대지의 동굴', 'ground.png'),

-- 2. 숲 (forest)
('forest', 'bug', '곤충의 숲', 'bug.png'),
('forest', 'electric', '번개나무 숲속', 'electric.png'),
('forest', 'flying', '하늘바람 숲', 'flying.png'),
('forest', 'ground', '황토 숲', 'ground.png'),
('forest', 'fire', '황토 숲', 'ground.png'),
('forest', 'poison', '독버섯 숲', 'poison.png'),
('forest', 'water', '물방울 나무터', 'water.png'),
('forest', 'dark', '어둠칠흑 밀림', 'dark.png'),
('forest', 'fairy', '요정의 숲', 'fairy.png'),
('forest', 'ghost', '안개 숲', 'ghost.png'),
('forest', 'ice', '눈꽃 숲', 'ice.png'),
('forest', 'rock', '돌길 수풀', 'rock.png'),
('forest', 'dragon', '고룡의 나무터', 'dragon.png'),
('forest', 'fighting', '수련의 숲', 'fighting.png'),
('forest', 'steel', '은빛 숲', 'steel.png'),
('forest', 'grass', '초록잎 숲', 'grass.png'),
('forest', 'normal', '초록잎 숲', 'grass.png'),
('forest', 'psychic', '초록잎 숲', 'grass.png'),

-- 3. 초원 (grassland)
('grassland', 'bug', '애벌레 언덕', 'bug.png'),
('grassland', 'dark', '그림자 평원', 'dark.png'),
('grassland', 'electric', '전하의 들판', 'electric.png'),
('grassland', 'fairy', '달빛 초원', 'fairy.png'),
('grassland', 'flying', '깃털 평원', 'flying.png'),
('grassland', 'ghost', '유령의 황야', 'ghost.png'),
('grassland', 'ground', '대지의 평원', 'ground.png'),
('grassland', 'ice', '서리꽃 들판', 'ice.png'),
('grassland', 'poison', '맹독의 들판', 'poison.png'),
('grassland', 'psychic', '영혼의 정원', 'psychic.png'),
('grassland', 'rock', '석영 들판', 'rock.png'),
('grassland', 'steel', '철광 초지', 'steel.png'),
('grassland', 'water', '호수 초원', 'water.png'),
('grassland', 'grass', '풀잎 초원', 'grass.png'),
('grassland', 'normal', '풀잎 초원', 'grass.png'),
('grassland', 'fire', '풀잎 초원', 'grass.png'),
('grassland', 'dragon', '풀잎 초원', 'grass.png'),
('grassland', 'fighting', '풀잎 초원', 'grass.png'),

-- 4. 산 (mountain)
('mountain', 'dark', '어둠골', 'dark.png'),
('mountain', 'dragon', '천룡대', 'dragon.png'),
('mountain', 'electric', '번개산', 'electric.png'),
('mountain', 'fairy', '달빛산', 'fairy.png'),
('mountain', 'fighting', '무혼봉', 'fighting.png'),
('mountain', 'fire', '화염산', 'fire.png'),
('mountain', 'flying', '천공봉', 'flying.png'),
('mountain', 'ground', '황토봉', 'ground.png'),
('mountain', 'ice', '설한봉', 'ice.png'),
('mountain', 'poison', '독안개산', 'poison.png'),
('mountain', 'psychic', '염력봉', 'psychic.png'),
('mountain', 'rock', '암벽봉', 'rock.png'),
('mountain', 'steel', '쇠붙이산', 'steel.png'),
('mountain', 'water', '해류봉', 'water.png'),
('mountain', 'grass', '청림산', 'grass.png'),
('mountain', 'normal', '청림산', 'grass.png'),
('mountain', 'bug', '청림산', 'grass.png'),
('mountain', 'ghost', '청림산', 'grass.png'),

-- 5. 험지 (roughterrain)
('roughterrain', 'dark', '암흑 협곡', 'dark.png'),
('roughterrain', 'dragon', '고룡 둥지', 'dragon.png'),
('roughterrain', 'electric', '천둥 고원', 'electric.png'),
('roughterrain', 'fighting', '투기장 협곡', 'fighting.png'),
('roughterrain', 'fire', '용암 협곡', 'fire.png'),
('roughterrain', 'flying', '구름 절벽', 'flying.png'),
('roughterrain', 'ground', '대지의 협곡', 'ground.png'),
('roughterrain', 'ice', '빙하 설원', 'ice.png'),
('roughterrain', 'poison', '오염된 늪지', 'poison.png'),
('roughterrain', 'psychic', '환영 사원', 'psychic.png'),
('roughterrain', 'rock', '암석 협곡', 'rock.png'),
('roughterrain', 'steel', '강철 폐허', 'steel.png'),
('roughterrain', 'water', '해안 절벽', 'water.png'),
('roughterrain', 'normal', '평범한 구릉', 'grass.png'),
('roughterrain', 'grass', '평범한 구릉', 'grass.png'),
('roughterrain', 'bug', '평범한 구릉', 'grass.png'),
('roughterrain', 'fairy', '평범한 구릉', 'grass.png'),
('roughterrain', 'ghost', '평범한 구릉', 'grass.png'),

-- 6. 바다 (sea)
('sea', 'flying', '하늘물결', 'flying.png'),
('sea', 'ice', '극한의바다', 'ice.png'),
('sea', 'rock', '암초해', 'rock.png'),
('sea', 'water', '깊은 바다', 'water.png'),
('sea', 'normal', '깊은 바다', 'water.png'),
('sea', 'bug', '깊은 바다', 'water.png'),
('sea', 'dark', '깊은 바다', 'water.png'),
('sea', 'dragon', '깊은 바다', 'water.png'),
('sea', 'electric', '깊은 바다', 'water.png'),
('sea', 'fairy', '깊은 바다', 'water.png'),
('sea', 'fighting', '깊은 바다', 'water.png'),
('sea', 'fire', '깊은 바다', 'water.png'),
('sea', 'ghost', '깊은 바다', 'water.png'),
('sea', 'grass', '깊은 바다', 'water.png'),
('sea', 'ground', '깊은 바다', 'water.png'),
('sea', 'poison', '깊은 바다', 'water.png'),
('sea', 'psychic', '깊은 바다', 'water.png'),
('sea', 'steel', '깊은 바다', 'water.png'),

-- 7. 도시 (urban)
('urban', 'bug', '딱정마을', 'bug.png'),
('urban', 'dark', '칠흑시티', 'dark.png'),
('urban', 'electric', '썬더볼트타운', 'electric.png'),
('urban', 'fairy', '반짝별마을', 'fairy.png'),
('urban', 'flying', '바람개비마을', 'flying.png'),
('urban', 'ghost', '유령저택촌', 'ghost.png'),
('urban', 'ground', '황토마을', 'ground.png'),
('urban', 'ice', '눈사람마을', 'ice.png'),
('urban', 'poison', '독안개촌', 'poison.png'),
('urban', 'psychic', '염력시티', 'psychic.png'),
('urban', 'rock', '암석시티', 'rock.png'),
('urban', 'steel', '공장촌', 'steel.png'),
('urban', 'water', '물결마을', 'water.png'),
('urban', 'normal', '일상의 마을', 'grass.png'),
('urban', 'grass', '일상의 마을', 'grass.png'),
('urban', 'fighting', '일상의 마을', 'grass.png'),
('urban', 'dragon', '일상의 마을', 'grass.png'),
('urban', 'fire', '일상의 마을', 'grass.png'),

-- 8. 물가 (watersedge)
('watersedge', 'electric', '번개호수', 'electric.png'),
('watersedge', 'fighting', '격투해변', 'fighting.png'),
('watersedge', 'flying', '구름개울', 'flying.png'),
('watersedge', 'ground', '황토강', 'ground.png'),
('watersedge', 'ice', '빙하호', 'ice.png'),
('watersedge', 'normal', '평온호수', 'water.png'),
('watersedge', 'psychic', '명상호', 'psychic.png'),
('watersedge', 'rock', '암석호', 'rock.png'),
('watersedge', 'water', '푸른호수', 'water.png'),
('watersedge', 'bug', '푸른호수', 'water.png'),
('watersedge', 'dark', '푸른호수', 'water.png'),
('watersedge', 'dragon', '푸른호수', 'water.png'),
('watersedge', 'fairy', '푸른호수', 'water.png'),
('watersedge', 'fire', '푸른호수', 'water.png'),
('watersedge', 'ghost', '푸른호수', 'water.png'),
('watersedge', 'grass', '푸른호수', 'water.png'),
('watersedge', 'poison', '푸른호수', 'water.png'),
('watersedge', 'steel', '푸른호수', 'water.png');
